<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class RegenciesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('regencies')->insert([
            ['regency_code' => '1101', 'province_code' => '11', 'regency_name' => 'KAB. ACEH SELATAN'],
            ['regency_code' => '1102', 'province_code' => '11', 'regency_name' => 'KAB. ACEH TENGGARA'],
            ['regency_code' => '1103', 'province_code' => '11', 'regency_name' => 'KAB. ACEH TIMUR'],
            ['regency_code' => '1104', 'province_code' => '11', 'regency_name' => 'KAB. ACEH TENGAH'],
            ['regency_code' => '1105', 'province_code' => '11', 'regency_name' => 'KAB. ACEH BARAT'],
            ['regency_code' => '1106', 'province_code' => '11', 'regency_name' => 'KAB. ACEH BESAR'],
            ['regency_code' => '1107', 'province_code' => '11', 'regency_name' => 'KAB. PIDIE'],
            ['regency_code' => '1108', 'province_code' => '11', 'regency_name' => 'KAB. ACEH UTARA'],
            ['regency_code' => '1109', 'province_code' => '11', 'regency_name' => 'KAB. SIMEULUE'],
            ['regency_code' => '1110', 'province_code' => '11', 'regency_name' => 'KAB. ACEH SINGKIL'],
            ['regency_code' => '1111', 'province_code' => '11', 'regency_name' => 'KAB. BIREUEN'],
            ['regency_code' => '1112', 'province_code' => '11', 'regency_name' => 'KAB. ACEH BARAT DAYA'],
            ['regency_code' => '1113', 'province_code' => '11', 'regency_name' => 'KAB. GAYO LUES'],
            ['regency_code' => '1114', 'province_code' => '11', 'regency_name' => 'KAB. ACEH JAYA'],
            ['regency_code' => '1115', 'province_code' => '11', 'regency_name' => 'KAB. NAGAN RAYA'],
            ['regency_code' => '1116', 'province_code' => '11', 'regency_name' => 'KAB. ACEH TAMIANG'],
            ['regency_code' => '1117', 'province_code' => '11', 'regency_name' => 'KAB. BENER MERIAH'],
            ['regency_code' => '1118', 'province_code' => '11', 'regency_name' => 'KAB. PIDIE JAYA'],
            ['regency_code' => '1171', 'province_code' => '11', 'regency_name' => 'KOTA BANDA ACEH'],
            ['regency_code' => '1172', 'province_code' => '11', 'regency_name' => 'KOTA SABANG'],
            ['regency_code' => '1173', 'province_code' => '11', 'regency_name' => 'KOTA LHOKSEUMAWE'],
            ['regency_code' => '1174', 'province_code' => '11', 'regency_name' => 'KOTA LANGSA'],
            ['regency_code' => '1175', 'province_code' => '11', 'regency_name' => 'KOTA SUBULUSSALAM'],
            ['regency_code' => '1201', 'province_code' => '12', 'regency_name' => 'KAB. TAPANULI TENGAH'],
            ['regency_code' => '1202', 'province_code' => '12', 'regency_name' => 'KAB. TAPANULI UTARA'],
            ['regency_code' => '1203', 'province_code' => '12', 'regency_name' => 'KAB. TAPANULI SELATAN'],
            ['regency_code' => '1204', 'province_code' => '12', 'regency_name' => 'KAB. NIAS'],
            ['regency_code' => '1205', 'province_code' => '12', 'regency_name' => 'KAB. LANGKAT'],
            ['regency_code' => '1206', 'province_code' => '12', 'regency_name' => 'KAB. KARO'],
            ['regency_code' => '1207', 'province_code' => '12', 'regency_name' => 'KAB. DELI SERDANG'],
            ['regency_code' => '1208', 'province_code' => '12', 'regency_name' => 'KAB. SIMALUNGUN'],
            ['regency_code' => '1209', 'province_code' => '12', 'regency_name' => 'KAB. ASAHAN'],
            ['regency_code' => '1210', 'province_code' => '12', 'regency_name' => 'KAB. LABUHANBATU'],
            ['regency_code' => '1211', 'province_code' => '12', 'regency_name' => 'KAB. DAIRI'],
            ['regency_code' => '1212', 'province_code' => '12', 'regency_name' => 'KAB. TOBA'],
            ['regency_code' => '1213', 'province_code' => '12', 'regency_name' => 'KAB. MANDAILING NATAL'],
            ['regency_code' => '1214', 'province_code' => '12', 'regency_name' => 'KAB. NIAS SELATAN'],
            ['regency_code' => '1215', 'province_code' => '12', 'regency_name' => 'KAB. PAKPAK BHARAT'],
            ['regency_code' => '1216', 'province_code' => '12', 'regency_name' => 'KAB. HUMBANG HASUNDUTAN'],
            ['regency_code' => '1217', 'province_code' => '12', 'regency_name' => 'KAB. SAMOSIR'],
            ['regency_code' => '1218', 'province_code' => '12', 'regency_name' => 'KAB. SERDANG BEDAGAI'],
            ['regency_code' => '1219', 'province_code' => '12', 'regency_name' => 'KAB. BATU BARA'],
            ['regency_code' => '1220', 'province_code' => '12', 'regency_name' => 'KAB. PADANG LAWAS UTARA'],
            ['regency_code' => '1221', 'province_code' => '12', 'regency_name' => 'KAB. PADANG LAWAS'],
            ['regency_code' => '1222', 'province_code' => '12', 'regency_name' => 'KAB. LABUHANBATU SELATAN'],
            ['regency_code' => '1223', 'province_code' => '12', 'regency_name' => 'KAB. LABUHANBATU UTARA'],
            ['regency_code' => '1224', 'province_code' => '12', 'regency_name' => 'KAB. NIAS UTARA'],
            ['regency_code' => '1225', 'province_code' => '12', 'regency_name' => 'KAB. NIAS BARAT'],
            ['regency_code' => '1271', 'province_code' => '12', 'regency_name' => 'KOTA MEDAN'],
            ['regency_code' => '1272', 'province_code' => '12', 'regency_name' => 'KOTA PEMATANGSIANTAR'],
            ['regency_code' => '1273', 'province_code' => '12', 'regency_name' => 'KOTA SIBOLGA'],
            ['regency_code' => '1274', 'province_code' => '12', 'regency_name' => 'KOTA TANJUNG BALAI'],
            ['regency_code' => '1275', 'province_code' => '12', 'regency_name' => 'KOTA BINJAI'],
            ['regency_code' => '1276', 'province_code' => '12', 'regency_name' => 'KOTA TEBING TINGGI'],
            ['regency_code' => '1277', 'province_code' => '12', 'regency_name' => 'KOTA PADANGSIDIMPUAN'],
            ['regency_code' => '1278', 'province_code' => '12', 'regency_name' => 'KOTA GUNUNGSITOLI'],
            ['regency_code' => '1301', 'province_code' => '13', 'regency_name' => 'KAB. PESISIR SELATAN'],
            ['regency_code' => '1302', 'province_code' => '13', 'regency_name' => 'KAB. SOLOK'],
            ['regency_code' => '1303', 'province_code' => '13', 'regency_name' => 'KAB. SIJUNJUNG'],
            ['regency_code' => '1304', 'province_code' => '13', 'regency_name' => 'KAB. TANAH DATAR'],
            ['regency_code' => '1305', 'province_code' => '13', 'regency_name' => 'KAB. PADANG PARIAMAN'],
            ['regency_code' => '1306', 'province_code' => '13', 'regency_name' => 'KAB. AGAM'],
            ['regency_code' => '1307', 'province_code' => '13', 'regency_name' => 'KAB. LIMA PULUH KOTA'],
            ['regency_code' => '1308', 'province_code' => '13', 'regency_name' => 'KAB. PASAMAN'],
            ['regency_code' => '1309', 'province_code' => '13', 'regency_name' => 'KAB. KEPULAUAN MENTAWAI'],
            ['regency_code' => '1310', 'province_code' => '13', 'regency_name' => 'KAB. DHARMASRAYA'],
            ['regency_code' => '1311', 'province_code' => '13', 'regency_name' => 'KAB. SOLOK SELATAN'],
            ['regency_code' => '1312', 'province_code' => '13', 'regency_name' => 'KAB. PASAMAN BARAT'],
            ['regency_code' => '1371', 'province_code' => '13', 'regency_name' => 'KOTA PADANG'],
            ['regency_code' => '1372', 'province_code' => '13', 'regency_name' => 'KOTA SOLOK'],
            ['regency_code' => '1373', 'province_code' => '13', 'regency_name' => 'KOTA SAWAHLUNTO'],
            ['regency_code' => '1374', 'province_code' => '13', 'regency_name' => 'KOTA PADANG PANJANG'],
            ['regency_code' => '1375', 'province_code' => '13', 'regency_name' => 'KOTA BUKITTINGGI'],
            ['regency_code' => '1376', 'province_code' => '13', 'regency_name' => 'KOTA PAYAKUMBUH'],
            ['regency_code' => '1377', 'province_code' => '13', 'regency_name' => 'KOTA PARIAMAN'],
            ['regency_code' => '1401', 'province_code' => '14', 'regency_name' => 'KAB. KAMPAR'],
            ['regency_code' => '1402', 'province_code' => '14', 'regency_name' => 'KAB. INDRAGIRI HULU'],
            ['regency_code' => '1403', 'province_code' => '14', 'regency_name' => 'KAB. BENGKALIS'],
            ['regency_code' => '1404', 'province_code' => '14', 'regency_name' => 'KAB. INDRAGIRI HILIR'],
            ['regency_code' => '1405', 'province_code' => '14', 'regency_name' => 'KAB. PELALAWAN'],
            ['regency_code' => '1406', 'province_code' => '14', 'regency_name' => 'KAB. ROKAN HULU'],
            ['regency_code' => '1407', 'province_code' => '14', 'regency_name' => 'KAB. ROKAN HILIR'],
            ['regency_code' => '1408', 'province_code' => '14', 'regency_name' => 'KAB. SIAK'],
            ['regency_code' => '1409', 'province_code' => '14', 'regency_name' => 'KAB. KUANTAN SINGINGI'],
            ['regency_code' => '1410', 'province_code' => '14', 'regency_name' => 'KAB. KEPULAUAN MERANTI'],
            ['regency_code' => '1471', 'province_code' => '14', 'regency_name' => 'KOTA PEKANBARU'],
            ['regency_code' => '1472', 'province_code' => '14', 'regency_name' => 'KOTA DUMAI'],
            ['regency_code' => '1501', 'province_code' => '15', 'regency_name' => 'KAB. KERINCI'],
            ['regency_code' => '1502', 'province_code' => '15', 'regency_name' => 'KAB. MERANGIN'],
            ['regency_code' => '1503', 'province_code' => '15', 'regency_name' => 'KAB. SAROLANGUN'],
            ['regency_code' => '1504', 'province_code' => '15', 'regency_name' => 'KAB. BATANGHARI'],
            ['regency_code' => '1505', 'province_code' => '15', 'regency_name' => 'KAB. MUARO JAMBI'],
            ['regency_code' => '1506', 'province_code' => '15', 'regency_name' => 'KAB. TANJUNG JABUNG BARAT'],
            ['regency_code' => '1507', 'province_code' => '15', 'regency_name' => 'KAB. TANJUNG JABUNG TIMUR'],
            ['regency_code' => '1508', 'province_code' => '15', 'regency_name' => 'KAB. BUNGO'],
            ['regency_code' => '1509', 'province_code' => '15', 'regency_name' => 'KAB. TEBO'],
            ['regency_code' => '1571', 'province_code' => '15', 'regency_name' => 'KOTA JAMBI'],
            ['regency_code' => '1572', 'province_code' => '15', 'regency_name' => 'KOTA SUNGAI PENUH'],
            ['regency_code' => '1601', 'province_code' => '16', 'regency_name' => 'KAB. OGAN KOMERING ULU'],
            ['regency_code' => '1602', 'province_code' => '16', 'regency_name' => 'KAB. OGAN KOMERING ILIR'],
            ['regency_code' => '1603', 'province_code' => '16', 'regency_name' => 'KAB. MUARA ENIM'],
            ['regency_code' => '1604', 'province_code' => '16', 'regency_name' => 'KAB. LAHAT'],
            ['regency_code' => '1605', 'province_code' => '16', 'regency_name' => 'KAB. MUSI RAWAS'],
            ['regency_code' => '1606', 'province_code' => '16', 'regency_name' => 'KAB. MUSI BANYUASIN'],
            ['regency_code' => '1607', 'province_code' => '16', 'regency_name' => 'KAB. BANYUASIN'],
            ['regency_code' => '1608', 'province_code' => '16', 'regency_name' => 'KAB. OGAN KOMERING ULU TIMUR'],
            ['regency_code' => '1609', 'province_code' => '16', 'regency_name' => 'KAB. OGAN KOMERING ULU SELATAN'],
            ['regency_code' => '1610', 'province_code' => '16', 'regency_name' => 'KAB. OGAN ILIR'],
            ['regency_code' => '1611', 'province_code' => '16', 'regency_name' => 'KAB. EMPAT LAWANG'],
            ['regency_code' => '1612', 'province_code' => '16', 'regency_name' => 'KAB. PENUKAL ABAB LEMATANG ILIR'],
            ['regency_code' => '1613', 'province_code' => '16', 'regency_name' => 'KAB. MUSI RAWAS UTARA'],
            ['regency_code' => '1671', 'province_code' => '16', 'regency_name' => 'KOTA PALEMBANG'],
            ['regency_code' => '1672', 'province_code' => '16', 'regency_name' => 'KOTA PAGAR ALAM'],
            ['regency_code' => '1673', 'province_code' => '16', 'regency_name' => 'KOTA LUBUK LINGGAU'],
            ['regency_code' => '1674', 'province_code' => '16', 'regency_name' => 'KOTA PRABUMULIH'],
            ['regency_code' => '1701', 'province_code' => '17', 'regency_name' => 'KAB. BENGKULU SELATAN'],
            ['regency_code' => '1702', 'province_code' => '17', 'regency_name' => 'KAB. REJANG LEBONG'],
            ['regency_code' => '1703', 'province_code' => '17', 'regency_name' => 'KAB. BENGKULU UTARA'],
            ['regency_code' => '1704', 'province_code' => '17', 'regency_name' => 'KAB. KAUR'],
            ['regency_code' => '1705', 'province_code' => '17', 'regency_name' => 'KAB. SELUMA'],
            ['regency_code' => '1706', 'province_code' => '17', 'regency_name' => 'KAB. MUKO MUKO'],
            ['regency_code' => '1707', 'province_code' => '17', 'regency_name' => 'KAB. LEBONG'],
            ['regency_code' => '1708', 'province_code' => '17', 'regency_name' => 'KAB. KEPAHIANG'],
            ['regency_code' => '1709', 'province_code' => '17', 'regency_name' => 'KAB. BENGKULU TENGAH'],
            ['regency_code' => '1771', 'province_code' => '17', 'regency_name' => 'KOTA BENGKULU'],
            ['regency_code' => '1801', 'province_code' => '18', 'regency_name' => 'KAB. LAMPUNG SELATAN'],
            ['regency_code' => '1802', 'province_code' => '18', 'regency_name' => 'KAB. LAMPUNG TENGAH'],
            ['regency_code' => '1803', 'province_code' => '18', 'regency_name' => 'KAB. LAMPUNG UTARA'],
            ['regency_code' => '1804', 'province_code' => '18', 'regency_name' => 'KAB. LAMPUNG BARAT'],
            ['regency_code' => '1805', 'province_code' => '18', 'regency_name' => 'KAB. TULANG BAWANG'],
            ['regency_code' => '1806', 'province_code' => '18', 'regency_name' => 'KAB. TANGGAMUS'],
            ['regency_code' => '1807', 'province_code' => '18', 'regency_name' => 'KAB. LAMPUNG TIMUR'],
            ['regency_code' => '1808', 'province_code' => '18', 'regency_name' => 'KAB. WAY KANAN'],
            ['regency_code' => '1809', 'province_code' => '18', 'regency_name' => 'KAB. PESAWARAN'],
            ['regency_code' => '1810', 'province_code' => '18', 'regency_name' => 'KAB. PRINGSEWU'],
            ['regency_code' => '1811', 'province_code' => '18', 'regency_name' => 'KAB. MESUJI'],
            ['regency_code' => '1812', 'province_code' => '18', 'regency_name' => 'KAB. TULANG BAWANG BARAT'],
            ['regency_code' => '1813', 'province_code' => '18', 'regency_name' => 'KAB. PESISIR BARAT'],
            ['regency_code' => '1871', 'province_code' => '18', 'regency_name' => 'KOTA BANDAR LAMPUNG'],
            ['regency_code' => '1872', 'province_code' => '18', 'regency_name' => 'KOTA METRO'],
            ['regency_code' => '1901', 'province_code' => '19', 'regency_name' => 'KAB. BANGKA'],
            ['regency_code' => '1902', 'province_code' => '19', 'regency_name' => 'KAB. BELITUNG'],
            ['regency_code' => '1903', 'province_code' => '19', 'regency_name' => 'KAB. BANGKA SELATAN'],
            ['regency_code' => '1904', 'province_code' => '19', 'regency_name' => 'KAB. BANGKA TENGAH'],
            ['regency_code' => '1905', 'province_code' => '19', 'regency_name' => 'KAB. BANGKA BARAT'],
            ['regency_code' => '1906', 'province_code' => '19', 'regency_name' => 'KAB. BELITUNG TIMUR'],
            ['regency_code' => '1971', 'province_code' => '19', 'regency_name' => 'KOTA PANGKAL PINANG'],
            ['regency_code' => '2101', 'province_code' => '21', 'regency_name' => 'KAB. BINTAN'],
            ['regency_code' => '2102', 'province_code' => '21', 'regency_name' => 'KAB. KARIMUN'],
            ['regency_code' => '2103', 'province_code' => '21', 'regency_name' => 'KAB. NATUNA'],
            ['regency_code' => '2104', 'province_code' => '21', 'regency_name' => 'KAB. LINGGA'],
            ['regency_code' => '2105', 'province_code' => '21', 'regency_name' => 'KAB. KEPULAUAN ANAMBAS'],
            ['regency_code' => '2171', 'province_code' => '21', 'regency_name' => 'KOTA BATAM'],
            ['regency_code' => '2172', 'province_code' => '21', 'regency_name' => 'KOTA TANJUNG PINANG'],
            ['regency_code' => '3101', 'province_code' => '31', 'regency_name' => 'KAB. ADM. KEP. SERIBU'],
            ['regency_code' => '3171', 'province_code' => '31', 'regency_name' => 'KOTA ADM. JAKARTA PUSAT'],
            ['regency_code' => '3172', 'province_code' => '31', 'regency_name' => 'KOTA ADM. JAKARTA UTARA'],
            ['regency_code' => '3173', 'province_code' => '31', 'regency_name' => 'KOTA ADM. JAKARTA BARAT'],
            ['regency_code' => '3174', 'province_code' => '31', 'regency_name' => 'KOTA ADM. JAKARTA SELATAN'],
            ['regency_code' => '3175', 'province_code' => '31', 'regency_name' => 'KOTA ADM. JAKARTA TIMUR'],
            ['regency_code' => '3201', 'province_code' => '32', 'regency_name' => 'KAB. BOGOR'],
            ['regency_code' => '3202', 'province_code' => '32', 'regency_name' => 'KAB. SUKABUMI'],
            ['regency_code' => '3203', 'province_code' => '32', 'regency_name' => 'KAB. CIANJUR'],
            ['regency_code' => '3204', 'province_code' => '32', 'regency_name' => 'KAB. BANDUNG'],
            ['regency_code' => '3205', 'province_code' => '32', 'regency_name' => 'KAB. GARUT'],
            ['regency_code' => '3206', 'province_code' => '32', 'regency_name' => 'KAB. TASIKMALAYA'],
            ['regency_code' => '3207', 'province_code' => '32', 'regency_name' => 'KAB. CIAMIS'],
            ['regency_code' => '3208', 'province_code' => '32', 'regency_name' => 'KAB. KUNINGAN'],
            ['regency_code' => '3209', 'province_code' => '32', 'regency_name' => 'KAB. CIREBON'],
            ['regency_code' => '3210', 'province_code' => '32', 'regency_name' => 'KAB. MAJALENGKA'],
            ['regency_code' => '3211', 'province_code' => '32', 'regency_name' => 'KAB. SUMEDANG'],
            ['regency_code' => '3212', 'province_code' => '32', 'regency_name' => 'KAB. INDRAMAYU'],
            ['regency_code' => '3213', 'province_code' => '32', 'regency_name' => 'KAB. SUBANG'],
            ['regency_code' => '3214', 'province_code' => '32', 'regency_name' => 'KAB. PURWAKARTA'],
            ['regency_code' => '3215', 'province_code' => '32', 'regency_name' => 'KAB. KARAWANG'],
            ['regency_code' => '3216', 'province_code' => '32', 'regency_name' => 'KAB. BEKASI'],
            ['regency_code' => '3217', 'province_code' => '32', 'regency_name' => 'KAB. BANDUNG BARAT'],
            ['regency_code' => '3218', 'province_code' => '32', 'regency_name' => 'KAB. PANGANDARAN'],
            ['regency_code' => '3271', 'province_code' => '32', 'regency_name' => 'KOTA BOGOR'],
            ['regency_code' => '3272', 'province_code' => '32', 'regency_name' => 'KOTA SUKABUMI'],
            ['regency_code' => '3273', 'province_code' => '32', 'regency_name' => 'KOTA BANDUNG'],
            ['regency_code' => '3274', 'province_code' => '32', 'regency_name' => 'KOTA CIREBON'],
            ['regency_code' => '3275', 'province_code' => '32', 'regency_name' => 'KOTA BEKASI'],
            ['regency_code' => '3276', 'province_code' => '32', 'regency_name' => 'KOTA DEPOK'],
            ['regency_code' => '3277', 'province_code' => '32', 'regency_name' => 'KOTA CIMAHI'],
            ['regency_code' => '3278', 'province_code' => '32', 'regency_name' => 'KOTA TASIKMALAYA'],
            ['regency_code' => '3279', 'province_code' => '32', 'regency_name' => 'KOTA BANJAR'],
            ['regency_code' => '3301', 'province_code' => '33', 'regency_name' => 'KAB. CILACAP'],
            ['regency_code' => '3302', 'province_code' => '33', 'regency_name' => 'KAB. BANYUMAS'],
            ['regency_code' => '3303', 'province_code' => '33', 'regency_name' => 'KAB. PURBALINGGA'],
            ['regency_code' => '3304', 'province_code' => '33', 'regency_name' => 'KAB. BANJARNEGARA'],
            ['regency_code' => '3305', 'province_code' => '33', 'regency_name' => 'KAB. KEBUMEN'],
            ['regency_code' => '3306', 'province_code' => '33', 'regency_name' => 'KAB. PURWOREJO'],
            ['regency_code' => '3307', 'province_code' => '33', 'regency_name' => 'KAB. WONOSOBO'],
            ['regency_code' => '3308', 'province_code' => '33', 'regency_name' => 'KAB. MAGELANG'],
            ['regency_code' => '3309', 'province_code' => '33', 'regency_name' => 'KAB. BOYOLALI'],
            ['regency_code' => '3310', 'province_code' => '33', 'regency_name' => 'KAB. KLATEN'],
            ['regency_code' => '3311', 'province_code' => '33', 'regency_name' => 'KAB. SUKOHARJO'],
            ['regency_code' => '3312', 'province_code' => '33', 'regency_name' => 'KAB. WONOGIRI'],
            ['regency_code' => '3313', 'province_code' => '33', 'regency_name' => 'KAB. KARANGANYAR'],
            ['regency_code' => '3314', 'province_code' => '33', 'regency_name' => 'KAB. SRAGEN'],
            ['regency_code' => '3315', 'province_code' => '33', 'regency_name' => 'KAB. GROBOGAN'],
            ['regency_code' => '3316', 'province_code' => '33', 'regency_name' => 'KAB. BLORA'],
            ['regency_code' => '3317', 'province_code' => '33', 'regency_name' => 'KAB. REMBANG'],
            ['regency_code' => '3318', 'province_code' => '33', 'regency_name' => 'KAB. PATI'],
            ['regency_code' => '3319', 'province_code' => '33', 'regency_name' => 'KAB. KUDUS'],
            ['regency_code' => '3320', 'province_code' => '33', 'regency_name' => 'KAB. JEPARA'],
            ['regency_code' => '3321', 'province_code' => '33', 'regency_name' => 'KAB. DEMAK'],
            ['regency_code' => '3322', 'province_code' => '33', 'regency_name' => 'KAB. SEMARANG'],
            ['regency_code' => '3323', 'province_code' => '33', 'regency_name' => 'KAB. TEMANGGUNG'],
            ['regency_code' => '3324', 'province_code' => '33', 'regency_name' => 'KAB. KENDAL'],
            ['regency_code' => '3325', 'province_code' => '33', 'regency_name' => 'KAB. BATANG'],
            ['regency_code' => '3326', 'province_code' => '33', 'regency_name' => 'KAB. PEKALONGAN'],
            ['regency_code' => '3327', 'province_code' => '33', 'regency_name' => 'KAB. PEMALANG'],
            ['regency_code' => '3328', 'province_code' => '33', 'regency_name' => 'KAB. TEGAL'],
            ['regency_code' => '3329', 'province_code' => '33', 'regency_name' => 'KAB. BREBES'],
            ['regency_code' => '3371', 'province_code' => '33', 'regency_name' => 'KOTA MAGELANG'],
            ['regency_code' => '3372', 'province_code' => '33', 'regency_name' => 'KOTA SURAKARTA'],
            ['regency_code' => '3373', 'province_code' => '33', 'regency_name' => 'KOTA SALATIGA'],
            ['regency_code' => '3374', 'province_code' => '33', 'regency_name' => 'KOTA SEMARANG'],
            ['regency_code' => '3375', 'province_code' => '33', 'regency_name' => 'KOTA PEKALONGAN'],
            ['regency_code' => '3376', 'province_code' => '33', 'regency_name' => 'KOTA TEGAL'],
            ['regency_code' => '3401', 'province_code' => '34', 'regency_name' => 'KAB. KULON PROGO'],
            ['regency_code' => '3402', 'province_code' => '34', 'regency_name' => 'KAB. BANTUL'],
            ['regency_code' => '3403', 'province_code' => '34', 'regency_name' => 'KAB. GUNUNGKIDUL'],
            ['regency_code' => '3404', 'province_code' => '34', 'regency_name' => 'KAB. SLEMAN'],
            ['regency_code' => '3471', 'province_code' => '34', 'regency_name' => 'KOTA YOGYAKARTA'],
            ['regency_code' => '3501', 'province_code' => '35', 'regency_name' => 'KAB. PACITAN'],
            ['regency_code' => '3502', 'province_code' => '35', 'regency_name' => 'KAB. PONOROGO'],
            ['regency_code' => '3503', 'province_code' => '35', 'regency_name' => 'KAB. TRENGGALEK'],
            ['regency_code' => '3504', 'province_code' => '35', 'regency_name' => 'KAB. TULUNGAGUNG'],
            ['regency_code' => '3505', 'province_code' => '35', 'regency_name' => 'KAB. BLITAR'],
            ['regency_code' => '3506', 'province_code' => '35', 'regency_name' => 'KAB. KEDIRI'],
            ['regency_code' => '3507', 'province_code' => '35', 'regency_name' => 'KAB. MALANG'],
            ['regency_code' => '3508', 'province_code' => '35', 'regency_name' => 'KAB. LUMAJANG'],
            ['regency_code' => '3509', 'province_code' => '35', 'regency_name' => 'KAB. JEMBER'],
            ['regency_code' => '3510', 'province_code' => '35', 'regency_name' => 'KAB. BANYUWANGI'],
            ['regency_code' => '3511', 'province_code' => '35', 'regency_name' => 'KAB. BONDOWOSO'],
            ['regency_code' => '3512', 'province_code' => '35', 'regency_name' => 'KAB. SITUBONDO'],
            ['regency_code' => '3513', 'province_code' => '35', 'regency_name' => 'KAB. PROBOLINGGO'],
            ['regency_code' => '3514', 'province_code' => '35', 'regency_name' => 'KAB. PASURUAN'],
            ['regency_code' => '3515', 'province_code' => '35', 'regency_name' => 'KAB. SIDOARJO'],
            ['regency_code' => '3516', 'province_code' => '35', 'regency_name' => 'KAB. MOJOKERTO'],
            ['regency_code' => '3517', 'province_code' => '35', 'regency_name' => 'KAB. JOMBANG'],
            ['regency_code' => '3518', 'province_code' => '35', 'regency_name' => 'KAB. NGANJUK'],
            ['regency_code' => '3519', 'province_code' => '35', 'regency_name' => 'KAB. MADIUN'],
            ['regency_code' => '3520', 'province_code' => '35', 'regency_name' => 'KAB. MAGETAN'],
            ['regency_code' => '3521', 'province_code' => '35', 'regency_name' => 'KAB. NGAWI'],
            ['regency_code' => '3522', 'province_code' => '35', 'regency_name' => 'KAB. BOJONEGORO'],
            ['regency_code' => '3523', 'province_code' => '35', 'regency_name' => 'KAB. TUBAN'],
            ['regency_code' => '3524', 'province_code' => '35', 'regency_name' => 'KAB. LAMONGAN'],
            ['regency_code' => '3525', 'province_code' => '35', 'regency_name' => 'KAB. GRESIK'],
            ['regency_code' => '3526', 'province_code' => '35', 'regency_name' => 'KAB. BANGKALAN'],
            ['regency_code' => '3527', 'province_code' => '35', 'regency_name' => 'KAB. SAMPANG'],
            ['regency_code' => '3528', 'province_code' => '35', 'regency_name' => 'KAB. PAMEKASAN'],
            ['regency_code' => '3529', 'province_code' => '35', 'regency_name' => 'KAB. SUMENEP'],
            ['regency_code' => '3571', 'province_code' => '35', 'regency_name' => 'KOTA KEDIRI'],
            ['regency_code' => '3572', 'province_code' => '35', 'regency_name' => 'KOTA BLITAR'],
            ['regency_code' => '3573', 'province_code' => '35', 'regency_name' => 'KOTA MALANG'],
            ['regency_code' => '3574', 'province_code' => '35', 'regency_name' => 'KOTA PROBOLINGGO'],
            ['regency_code' => '3575', 'province_code' => '35', 'regency_name' => 'KOTA PASURUAN'],
            ['regency_code' => '3576', 'province_code' => '35', 'regency_name' => 'KOTA MOJOKERTO'],
            ['regency_code' => '3577', 'province_code' => '35', 'regency_name' => 'KOTA MADIUN'],
            ['regency_code' => '3578', 'province_code' => '35', 'regency_name' => 'KOTA SURABAYA'],
            ['regency_code' => '3579', 'province_code' => '35', 'regency_name' => 'KOTA BATU'],
            ['regency_code' => '3601', 'province_code' => '36', 'regency_name' => 'KAB. PANDEGLANG'],
            ['regency_code' => '3602', 'province_code' => '36', 'regency_name' => 'KAB. LEBAK'],
            ['regency_code' => '3603', 'province_code' => '36', 'regency_name' => 'KAB. TANGERANG'],
            ['regency_code' => '3604', 'province_code' => '36', 'regency_name' => 'KAB. SERANG'],
            ['regency_code' => '3671', 'province_code' => '36', 'regency_name' => 'KOTA TANGERANG'],
            ['regency_code' => '3672', 'province_code' => '36', 'regency_name' => 'KOTA CILEGON'],
            ['regency_code' => '3673', 'province_code' => '36', 'regency_name' => 'KOTA SERANG'],
            ['regency_code' => '3674', 'province_code' => '36', 'regency_name' => 'KOTA TANGERANG SELATAN'],
            ['regency_code' => '5101', 'province_code' => '51', 'regency_name' => 'KAB. JEMBRANA'],
            ['regency_code' => '5102', 'province_code' => '51', 'regency_name' => 'KAB. TABANAN'],
            ['regency_code' => '5103', 'province_code' => '51', 'regency_name' => 'KAB. BADUNG'],
            ['regency_code' => '5104', 'province_code' => '51', 'regency_name' => 'KAB. GIANYAR'],
            ['regency_code' => '5105', 'province_code' => '51', 'regency_name' => 'KAB. KLUNGKUNG'],
            ['regency_code' => '5106', 'province_code' => '51', 'regency_name' => 'KAB. BANGLI'],
            ['regency_code' => '5107', 'province_code' => '51', 'regency_name' => 'KAB. KARANGASEM'],
            ['regency_code' => '5108', 'province_code' => '51', 'regency_name' => 'KAB. BULELENG'],
            ['regency_code' => '5171', 'province_code' => '51', 'regency_name' => 'KOTA DENPASAR'],
            ['regency_code' => '5201', 'province_code' => '52', 'regency_name' => 'KAB. LOMBOK BARAT'],
            ['regency_code' => '5202', 'province_code' => '52', 'regency_name' => 'KAB. LOMBOK TENGAH'],
            ['regency_code' => '5203', 'province_code' => '52', 'regency_name' => 'KAB. LOMBOK TIMUR'],
            ['regency_code' => '5204', 'province_code' => '52', 'regency_name' => 'KAB. SUMBAWA'],
            ['regency_code' => '5205', 'province_code' => '52', 'regency_name' => 'KAB. DOMPU'],
            ['regency_code' => '5206', 'province_code' => '52', 'regency_name' => 'KAB. BIMA'],
            ['regency_code' => '5207', 'province_code' => '52', 'regency_name' => 'KAB. SUMBAWA BARAT'],
            ['regency_code' => '5208', 'province_code' => '52', 'regency_name' => 'KAB. LOMBOK UTARA'],
            ['regency_code' => '5271', 'province_code' => '52', 'regency_name' => 'KOTA MATARAM'],
            ['regency_code' => '5272', 'province_code' => '52', 'regency_name' => 'KOTA BIMA'],
            ['regency_code' => '5301', 'province_code' => '53', 'regency_name' => 'KAB. KUPANG'],
            ['regency_code' => '5302', 'province_code' => '53', 'regency_name' => 'KAB TIMOR TENGAH SELATAN'],
            ['regency_code' => '5303', 'province_code' => '53', 'regency_name' => 'KAB. TIMOR TENGAH UTARA'],
            ['regency_code' => '5304', 'province_code' => '53', 'regency_name' => 'KAB. BELU'],
            ['regency_code' => '5305', 'province_code' => '53', 'regency_name' => 'KAB. ALOR'],
            ['regency_code' => '5306', 'province_code' => '53', 'regency_name' => 'KAB. FLORES TIMUR'],
            ['regency_code' => '5307', 'province_code' => '53', 'regency_name' => 'KAB. SIKKA'],
            ['regency_code' => '5308', 'province_code' => '53', 'regency_name' => 'KAB. ENDE'],
            ['regency_code' => '5309', 'province_code' => '53', 'regency_name' => 'KAB. NGADA'],
            ['regency_code' => '5310', 'province_code' => '53', 'regency_name' => 'KAB. MANGGARAI'],
            ['regency_code' => '5311', 'province_code' => '53', 'regency_name' => 'KAB. SUMBA TIMUR'],
            ['regency_code' => '5312', 'province_code' => '53', 'regency_name' => 'KAB. SUMBA BARAT'],
            ['regency_code' => '5313', 'province_code' => '53', 'regency_name' => 'KAB. LEMBATA'],
            ['regency_code' => '5314', 'province_code' => '53', 'regency_name' => 'KAB. ROTE NDAO'],
            ['regency_code' => '5315', 'province_code' => '53', 'regency_name' => 'KAB. MANGGARAI BARAT'],
            ['regency_code' => '5316', 'province_code' => '53', 'regency_name' => 'KAB. NAGEKEO'],
            ['regency_code' => '5317', 'province_code' => '53', 'regency_name' => 'KAB. SUMBA TENGAH'],
            ['regency_code' => '5318', 'province_code' => '53', 'regency_name' => 'KAB. SUMBA BARAT DAYA'],
            ['regency_code' => '5319', 'province_code' => '53', 'regency_name' => 'KAB. MANGGARAI TIMUR'],
            ['regency_code' => '5320', 'province_code' => '53', 'regency_name' => 'KAB. SABU RAIJUA'],
            ['regency_code' => '5321', 'province_code' => '53', 'regency_name' => 'KAB. MALAKA'],
            ['regency_code' => '5371', 'province_code' => '53', 'regency_name' => 'KOTA KUPANG'],
            ['regency_code' => '6101', 'province_code' => '61', 'regency_name' => 'KAB. SAMBAS'],
            ['regency_code' => '6102', 'province_code' => '61', 'regency_name' => 'KAB. MEMPAWAH'],
            ['regency_code' => '6103', 'province_code' => '61', 'regency_name' => 'KAB. SANGGAU'],
            ['regency_code' => '6104', 'province_code' => '61', 'regency_name' => 'KAB. KETAPANG'],
            ['regency_code' => '6105', 'province_code' => '61', 'regency_name' => 'KAB. SINTANG'],
            ['regency_code' => '6106', 'province_code' => '61', 'regency_name' => 'KAB. KAPUAS HULU'],
            ['regency_code' => '6107', 'province_code' => '61', 'regency_name' => 'KAB. BENGKAYANG'],
            ['regency_code' => '6108', 'province_code' => '61', 'regency_name' => 'KAB. LANDAK'],
            ['regency_code' => '6109', 'province_code' => '61', 'regency_name' => 'KAB. SEKADAU'],
            ['regency_code' => '6110', 'province_code' => '61', 'regency_name' => 'KAB. MELAWI'],
            ['regency_code' => '6111', 'province_code' => '61', 'regency_name' => 'KAB. KAYONG UTARA'],
            ['regency_code' => '6112', 'province_code' => '61', 'regency_name' => 'KAB. KUBU RAYA'],
            ['regency_code' => '6171', 'province_code' => '61', 'regency_name' => 'KOTA PONTIANAK'],
            ['regency_code' => '6172', 'province_code' => '61', 'regency_name' => 'KOTA SINGKAWANG'],
            ['regency_code' => '6201', 'province_code' => '62', 'regency_name' => 'KAB. KOTAWARINGIN BARAT'],
            ['regency_code' => '6202', 'province_code' => '62', 'regency_name' => 'KAB. KOTAWARINGIN TIMUR'],
            ['regency_code' => '6203', 'province_code' => '62', 'regency_name' => 'KAB. KAPUAS'],
            ['regency_code' => '6204', 'province_code' => '62', 'regency_name' => 'KAB. BARITO SELATAN'],
            ['regency_code' => '6205', 'province_code' => '62', 'regency_name' => 'KAB. BARITO UTARA'],
            ['regency_code' => '6206', 'province_code' => '62', 'regency_name' => 'KAB. KATINGAN'],
            ['regency_code' => '6207', 'province_code' => '62', 'regency_name' => 'KAB. SERUYAN'],
            ['regency_code' => '6208', 'province_code' => '62', 'regency_name' => 'KAB. SUKAMARA'],
            ['regency_code' => '6209', 'province_code' => '62', 'regency_name' => 'KAB. LAMANDAU'],
            ['regency_code' => '6210', 'province_code' => '62', 'regency_name' => 'KAB. GUNUNG MAS'],
            ['regency_code' => '6211', 'province_code' => '62', 'regency_name' => 'KAB. PULANG PISAU'],
            ['regency_code' => '6212', 'province_code' => '62', 'regency_name' => 'KAB. MURUNG RAYA'],
            ['regency_code' => '6213', 'province_code' => '62', 'regency_name' => 'KAB. BARITO TIMUR'],
            ['regency_code' => '6271', 'province_code' => '62', 'regency_name' => 'KOTA PALANGKARAYA'],
            ['regency_code' => '6301', 'province_code' => '63', 'regency_name' => 'KAB. TANAH LAUT'],
            ['regency_code' => '6302', 'province_code' => '63', 'regency_name' => 'KAB. KOTABARU'],
            ['regency_code' => '6303', 'province_code' => '63', 'regency_name' => 'KAB. BANJAR'],
            ['regency_code' => '6304', 'province_code' => '63', 'regency_name' => 'KAB. BARITO KUALA'],
            ['regency_code' => '6305', 'province_code' => '63', 'regency_name' => 'KAB. TAPIN'],
            ['regency_code' => '6306', 'province_code' => '63', 'regency_name' => 'KAB. HULU SUNGAI SELATAN'],
            ['regency_code' => '6307', 'province_code' => '63', 'regency_name' => 'KAB. HULU SUNGAI TENGAH'],
            ['regency_code' => '6308', 'province_code' => '63', 'regency_name' => 'KAB. HULU SUNGAI UTARA'],
            ['regency_code' => '6309', 'province_code' => '63', 'regency_name' => 'KAB. TABALONG'],
            ['regency_code' => '6310', 'province_code' => '63', 'regency_name' => 'KAB. TANAH BUMBU'],
            ['regency_code' => '6311', 'province_code' => '63', 'regency_name' => 'KAB. BALANGAN'],
            ['regency_code' => '6371', 'province_code' => '63', 'regency_name' => 'KOTA BANJARMASIN'],
            ['regency_code' => '6372', 'province_code' => '63', 'regency_name' => 'KOTA BANJARBARU'],
            ['regency_code' => '6401', 'province_code' => '64', 'regency_name' => 'KAB. PASER'],
            ['regency_code' => '6402', 'province_code' => '64', 'regency_name' => 'KAB. KUTAI KARTANEGARA'],
            ['regency_code' => '6403', 'province_code' => '64', 'regency_name' => 'KAB. BERAU'],
            ['regency_code' => '6407', 'province_code' => '64', 'regency_name' => 'KAB. KUTAI BARAT'],
            ['regency_code' => '6408', 'province_code' => '64', 'regency_name' => 'KAB. KUTAI TIMUR'],
            ['regency_code' => '6409', 'province_code' => '64', 'regency_name' => 'KAB. PENAJAM PASER UTARA'],
            ['regency_code' => '6411', 'province_code' => '64', 'regency_name' => 'KAB. MAHAKAM ULU'],
            ['regency_code' => '6471', 'province_code' => '64', 'regency_name' => 'KOTA BALIKPAPAN'],
            ['regency_code' => '6472', 'province_code' => '64', 'regency_name' => 'KOTA SAMARINDA'],
            ['regency_code' => '6474', 'province_code' => '64', 'regency_name' => 'KOTA BONTANG'],
            ['regency_code' => '6501', 'province_code' => '65', 'regency_name' => 'KAB. BULUNGAN'],
            ['regency_code' => '6502', 'province_code' => '65', 'regency_name' => 'KAB. MALINAU'],
            ['regency_code' => '6503', 'province_code' => '65', 'regency_name' => 'KAB. NUNUKAN'],
            ['regency_code' => '6504', 'province_code' => '65', 'regency_name' => 'KAB. TANA TIDUNG'],
            ['regency_code' => '6571', 'province_code' => '65', 'regency_name' => 'KOTA TARAKAN'],
            ['regency_code' => '7101', 'province_code' => '71', 'regency_name' => 'KAB. BOLAANG MONGONDOW'],
            ['regency_code' => '7102', 'province_code' => '71', 'regency_name' => 'KAB. MINAHASA'],
            ['regency_code' => '7103', 'province_code' => '71', 'regency_name' => 'KAB. KEPULAUAN SANGIHE'],
            ['regency_code' => '7104', 'province_code' => '71', 'regency_name' => 'KAB. KEPULAUAN TALAUD'],
            ['regency_code' => '7105', 'province_code' => '71', 'regency_name' => 'KAB. MINAHASA SELATAN'],
            ['regency_code' => '7106', 'province_code' => '71', 'regency_name' => 'KAB. MINAHASA UTARA'],
            ['regency_code' => '7107', 'province_code' => '71', 'regency_name' => 'KAB. MINAHASA TENGGARA'],
            ['regency_code' => '7108', 'province_code' => '71', 'regency_name' => 'KAB. BOLAANG MONGONDOW UTARA'],
            ['regency_code' => '7109', 'province_code' => '71', 'regency_name' => 'KAB. KEP. SIAU TAGULANDANG BIARO'],
            ['regency_code' => '7110', 'province_code' => '71', 'regency_name' => 'KAB. BOLAANG MONGONDOW TIMUR'],
            ['regency_code' => '7111', 'province_code' => '71', 'regency_name' => 'KAB. BOLAANG MONGONDOW SELATAN'],
            ['regency_code' => '7171', 'province_code' => '71', 'regency_name' => 'KOTA MANADO'],
            ['regency_code' => '7172', 'province_code' => '71', 'regency_name' => 'KOTA BITUNG'],
            ['regency_code' => '7173', 'province_code' => '71', 'regency_name' => 'KOTA TOMOHON'],
            ['regency_code' => '7174', 'province_code' => '71', 'regency_name' => 'KOTA KOTAMOBAGU'],
            ['regency_code' => '7201', 'province_code' => '72', 'regency_name' => 'KAB. BANGGAI'],
            ['regency_code' => '7202', 'province_code' => '72', 'regency_name' => 'KAB. POSO'],
            ['regency_code' => '7203', 'province_code' => '72', 'regency_name' => 'KAB. DONGGALA'],
            ['regency_code' => '7204', 'province_code' => '72', 'regency_name' => 'KAB. TOLI TOLI'],
            ['regency_code' => '7205', 'province_code' => '72', 'regency_name' => 'KAB. BUOL'],
            ['regency_code' => '7206', 'province_code' => '72', 'regency_name' => 'KAB. MOROWALI'],
            ['regency_code' => '7207', 'province_code' => '72', 'regency_name' => 'KAB. BANGGAI KEPULAUAN'],
            ['regency_code' => '7208', 'province_code' => '72', 'regency_name' => 'KAB. PARIGI MOUTONG'],
            ['regency_code' => '7209', 'province_code' => '72', 'regency_name' => 'KAB. TOJO UNA UNA'],
            ['regency_code' => '7210', 'province_code' => '72', 'regency_name' => 'KAB. SIGI'],
            ['regency_code' => '7211', 'province_code' => '72', 'regency_name' => 'KAB. BANGGAI LAUT'],
            ['regency_code' => '7212', 'province_code' => '72', 'regency_name' => 'KAB. MOROWALI UTARA'],
            ['regency_code' => '7271', 'province_code' => '72', 'regency_name' => 'KOTA PALU'],
            ['regency_code' => '7301', 'province_code' => '73', 'regency_name' => 'KAB. KEPULAUAN SELAYAR'],
            ['regency_code' => '7302', 'province_code' => '73', 'regency_name' => 'KAB. BULUKUMBA'],
            ['regency_code' => '7303', 'province_code' => '73', 'regency_name' => 'KAB. BANTAENG'],
            ['regency_code' => '7304', 'province_code' => '73', 'regency_name' => 'KAB. JENEPONTO'],
            ['regency_code' => '7305', 'province_code' => '73', 'regency_name' => 'KAB. TAKALAR'],
            ['regency_code' => '7306', 'province_code' => '73', 'regency_name' => 'KAB. GOWA'],
            ['regency_code' => '7307', 'province_code' => '73', 'regency_name' => 'KAB. SINJAI'],
            ['regency_code' => '7308', 'province_code' => '73', 'regency_name' => 'KAB. BONE'],
            ['regency_code' => '7309', 'province_code' => '73', 'regency_name' => 'KAB. MAROS'],
            ['regency_code' => '7310', 'province_code' => '73', 'regency_name' => 'KAB. PANGKAJENE KEPULAUAN'],
            ['regency_code' => '7311', 'province_code' => '73', 'regency_name' => 'KAB. BARRU'],
            ['regency_code' => '7312', 'province_code' => '73', 'regency_name' => 'KAB. SOPPENG'],
            ['regency_code' => '7313', 'province_code' => '73', 'regency_name' => 'KAB. WAJO'],
            ['regency_code' => '7314', 'province_code' => '73', 'regency_name' => 'KAB. SIDENRENG RAPPANG'],
            ['regency_code' => '7315', 'province_code' => '73', 'regency_name' => 'KAB. PINRANG'],
            ['regency_code' => '7316', 'province_code' => '73', 'regency_name' => 'KAB. ENREKANG'],
            ['regency_code' => '7317', 'province_code' => '73', 'regency_name' => 'KAB. LUWU'],
            ['regency_code' => '7318', 'province_code' => '73', 'regency_name' => 'KAB. TANA TORAJA'],
            ['regency_code' => '7322', 'province_code' => '73', 'regency_name' => 'KAB. LUWU UTARA'],
            ['regency_code' => '7324', 'province_code' => '73', 'regency_name' => 'KAB. LUWU TIMUR'],
            ['regency_code' => '7326', 'province_code' => '73', 'regency_name' => 'KAB. TORAJA UTARA'],
            ['regency_code' => '7371', 'province_code' => '73', 'regency_name' => 'KOTA MAKASSAR'],
            ['regency_code' => '7372', 'province_code' => '73', 'regency_name' => 'KOTA PARE PARE'],
            ['regency_code' => '7373', 'province_code' => '73', 'regency_name' => 'KOTA PALOPO'],
            ['regency_code' => '7401', 'province_code' => '74', 'regency_name' => 'KAB. KOLAKA'],
            ['regency_code' => '7402', 'province_code' => '74', 'regency_name' => 'KAB. KONAWE'],
            ['regency_code' => '7403', 'province_code' => '74', 'regency_name' => 'KAB. MUNA'],
            ['regency_code' => '7404', 'province_code' => '74', 'regency_name' => 'KAB. BUTON'],
            ['regency_code' => '7405', 'province_code' => '74', 'regency_name' => 'KAB. KONAWE SELATAN'],
            ['regency_code' => '7406', 'province_code' => '74', 'regency_name' => 'KAB. BOMBANA'],
            ['regency_code' => '7407', 'province_code' => '74', 'regency_name' => 'KAB. WAKATOBI'],
            ['regency_code' => '7408', 'province_code' => '74', 'regency_name' => 'KAB. KOLAKA UTARA'],
            ['regency_code' => '7409', 'province_code' => '74', 'regency_name' => 'KAB. KONAWE UTARA'],
            ['regency_code' => '7410', 'province_code' => '74', 'regency_name' => 'KAB. BUTON UTARA'],
            ['regency_code' => '7411', 'province_code' => '74', 'regency_name' => 'KAB. KOLAKA TIMUR'],
            ['regency_code' => '7412', 'province_code' => '74', 'regency_name' => 'KAB. KONAWE KEPULAUAN'],
            ['regency_code' => '7413', 'province_code' => '74', 'regency_name' => 'KAB. MUNA BARAT'],
            ['regency_code' => '7414', 'province_code' => '74', 'regency_name' => 'KAB. BUTON TENGAH'],
            ['regency_code' => '7415', 'province_code' => '74', 'regency_name' => 'KAB. BUTON SELATAN'],
            ['regency_code' => '7471', 'province_code' => '74', 'regency_name' => 'KOTA KENDARI'],
            ['regency_code' => '7472', 'province_code' => '74', 'regency_name' => 'KOTA BAU BAU'],
            ['regency_code' => '7501', 'province_code' => '75', 'regency_name' => 'KAB. GORONTALO'],
            ['regency_code' => '7502', 'province_code' => '75', 'regency_name' => 'KAB. BOALEMO'],
            ['regency_code' => '7503', 'province_code' => '75', 'regency_name' => 'KAB. BONE BOLANGO'],
            ['regency_code' => '7504', 'province_code' => '75', 'regency_name' => 'KAB. POHUWATO'],
            ['regency_code' => '7505', 'province_code' => '75', 'regency_name' => 'KAB. GORONTALO UTARA'],
            ['regency_code' => '7571', 'province_code' => '75', 'regency_name' => 'KOTA GORONTALO'],
            ['regency_code' => '7601', 'province_code' => '76', 'regency_name' => 'KAB. PASANGKAYU'],
            ['regency_code' => '7602', 'province_code' => '76', 'regency_name' => 'KAB. MAMUJU'],
            ['regency_code' => '7603', 'province_code' => '76', 'regency_name' => 'KAB. MAMASA'],
            ['regency_code' => '7604', 'province_code' => '76', 'regency_name' => 'KAB. POLEWALI MANDAR'],
            ['regency_code' => '7605', 'province_code' => '76', 'regency_name' => 'KAB. MAJENE'],
            ['regency_code' => '7606', 'province_code' => '76', 'regency_name' => 'KAB. MAMUJU TENGAH'],
            ['regency_code' => '8101', 'province_code' => '81', 'regency_name' => 'KAB. MALUKU TENGAH'],
            ['regency_code' => '8102', 'province_code' => '81', 'regency_name' => 'KAB. MALUKU TENGGARA'],
            ['regency_code' => '8103', 'province_code' => '81', 'regency_name' => 'KAB. KEPULAUAN TANIMBAR'],
            ['regency_code' => '8104', 'province_code' => '81', 'regency_name' => 'KAB. BURU'],
            ['regency_code' => '8105', 'province_code' => '81', 'regency_name' => 'KAB. SERAM BAGIAN TIMUR'],
            ['regency_code' => '8106', 'province_code' => '81', 'regency_name' => 'KAB. SERAM BAGIAN BARAT'],
            ['regency_code' => '8107', 'province_code' => '81', 'regency_name' => 'KAB. KEPULAUAN ARU'],
            ['regency_code' => '8108', 'province_code' => '81', 'regency_name' => 'KAB. MALUKU BARAT DAYA'],
            ['regency_code' => '8109', 'province_code' => '81', 'regency_name' => 'KAB. BURU SELATAN'],
            ['regency_code' => '8171', 'province_code' => '81', 'regency_name' => 'KOTA AMBON'],
            ['regency_code' => '8172', 'province_code' => '81', 'regency_name' => 'KOTA TUAL'],
            ['regency_code' => '8201', 'province_code' => '82', 'regency_name' => 'KAB. HALMAHERA BARAT'],
            ['regency_code' => '8202', 'province_code' => '82', 'regency_name' => 'KAB. HALMAHERA TENGAH'],
            ['regency_code' => '8203', 'province_code' => '82', 'regency_name' => 'KAB. HALMAHERA UTARA'],
            ['regency_code' => '8204', 'province_code' => '82', 'regency_name' => 'KAB. HALMAHERA SELATAN'],
            ['regency_code' => '8205', 'province_code' => '82', 'regency_name' => 'KAB. KEPULAUAN SULA'],
            ['regency_code' => '8206', 'province_code' => '82', 'regency_name' => 'KAB. HALMAHERA TIMUR'],
            ['regency_code' => '8207', 'province_code' => '82', 'regency_name' => 'KAB. PULAU MOROTAI'],
            ['regency_code' => '8208', 'province_code' => '82', 'regency_name' => 'KAB. PULAU TALIABU'],
            ['regency_code' => '8271', 'province_code' => '82', 'regency_name' => 'KOTA TERNATE'],
            ['regency_code' => '8272', 'province_code' => '82', 'regency_name' => 'KOTA TIDORE KEPULAUAN'],
            ['regency_code' => '9103', 'province_code' => '91', 'regency_name' => 'KAB. JAYAPURA'],
            ['regency_code' => '9105', 'province_code' => '91', 'regency_name' => 'KAB. KEPULAUAN YAPEN'],
            ['regency_code' => '9106', 'province_code' => '91', 'regency_name' => 'KAB. BIAK NUMFOR'],
            ['regency_code' => '9110', 'province_code' => '91', 'regency_name' => 'KAB. SARMI'],
            ['regency_code' => '9111', 'province_code' => '91', 'regency_name' => 'KAB. KEEROM'],
            ['regency_code' => '9115', 'province_code' => '91', 'regency_name' => 'KAB. WAROPEN'],
            ['regency_code' => '9119', 'province_code' => '91', 'regency_name' => 'KAB. SUPIORI'],
            ['regency_code' => '9120', 'province_code' => '91', 'regency_name' => 'KAB. MAMBERAMO RAYA'],
            ['regency_code' => '9171', 'province_code' => '91', 'regency_name' => 'KOTA JAYAPURA'],
            ['regency_code' => '9201', 'province_code' => '92', 'regency_name' => 'KAB. SORONG'],
            ['regency_code' => '9202', 'province_code' => '92', 'regency_name' => 'KAB. MANOKWARI'],
            ['regency_code' => '9203', 'province_code' => '92', 'regency_name' => 'KAB. FAK FAK'],
            ['regency_code' => '9204', 'province_code' => '92', 'regency_name' => 'KAB. SORONG SELATAN'],
            ['regency_code' => '9205', 'province_code' => '92', 'regency_name' => 'KAB. RAJA AMPAT'],
            ['regency_code' => '9206', 'province_code' => '92', 'regency_name' => 'KAB. TELUK BINTUNI'],
            ['regency_code' => '9207', 'province_code' => '92', 'regency_name' => 'KAB. TELUK WONDAMA'],
            ['regency_code' => '9208', 'province_code' => '92', 'regency_name' => 'KAB. KAIMANA'],
            ['regency_code' => '9209', 'province_code' => '92', 'regency_name' => 'KAB. TAMBRAUW'],
            ['regency_code' => '9210', 'province_code' => '92', 'regency_name' => 'KAB. MAYBRAT'],
            ['regency_code' => '9211', 'province_code' => '92', 'regency_name' => 'KAB. MANOKWARI SELATAN'],
            ['regency_code' => '9212', 'province_code' => '92', 'regency_name' => 'KAB. PEGUNUNGAN ARFAK'],
            ['regency_code' => '9271', 'province_code' => '92', 'regency_name' => 'KOTA SORONG'],
            ['regency_code' => '9301', 'province_code' => '93', 'regency_name' => 'KAB. MERAUKE'],
            ['regency_code' => '9302', 'province_code' => '93', 'regency_name' => 'KAB. BOVEN DIGOEL'],
            ['regency_code' => '9303', 'province_code' => '93', 'regency_name' => 'KAB. MAPPI'],
            ['regency_code' => '9304', 'province_code' => '93', 'regency_name' => 'KAB. ASMAT'],
            ['regency_code' => '9401', 'province_code' => '94', 'regency_name' => 'KAB. NABIRE'],
            ['regency_code' => '9402', 'province_code' => '94', 'regency_name' => 'KAB. PUNCAK JAYA'],
            ['regency_code' => '9403', 'province_code' => '94', 'regency_name' => 'KAB. PANIAI'],
            ['regency_code' => '9404', 'province_code' => '94', 'regency_name' => 'KAB. MIMIKA'],
            ['regency_code' => '9405', 'province_code' => '94', 'regency_name' => 'KAB. PUNCAK'],
            ['regency_code' => '9406', 'province_code' => '94', 'regency_name' => 'KAB. DOGIYAI'],
            ['regency_code' => '9407', 'province_code' => '94', 'regency_name' => 'KAB. INTAN JAYA'],
            ['regency_code' => '9408', 'province_code' => '94', 'regency_name' => 'KAB. DEIYAI'],
            ['regency_code' => '9501', 'province_code' => '95', 'regency_name' => 'KAB. JAYAWIJAYA'],
            ['regency_code' => '9502', 'province_code' => '95', 'regency_name' => 'KAB. PEGUNUNGAN BINTANG'],
            ['regency_code' => '9503', 'province_code' => '95', 'regency_name' => 'KAB. YAHUKIMO'],
            ['regency_code' => '9504', 'province_code' => '95', 'regency_name' => 'KAB. TOLIKARA'],
            ['regency_code' => '9505', 'province_code' => '95', 'regency_name' => 'KAB. MAMBERAMO TENGAH'],
            ['regency_code' => '9506', 'province_code' => '95', 'regency_name' => 'KAB. YALIMO'],
            ['regency_code' => '9507', 'province_code' => '95', 'regency_name' => 'KAB. LANNY JAYA'],
            ['regency_code' => '9508', 'province_code' => '95', 'regency_name' => 'KAB. NDUGA'],
        ]);
    }
}
